{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "sonarqube.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ .Values.ingress.labels | toYaml | trimSuffix "\n" | indent 4 }}
{{- end }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ .Values.ingress.annotations | toYaml | trimSuffix "\n" | indent 4 }}
{{- end }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ (index .Values.ingress.hosts 0).name }}
    secretName: {{ (index .Values.ingress.hosts 0).tls }}
{{- if .Values.ingress.customCACert }}
    caCertificate: # Use the secret containing the CA certificate
      secretName: ingress-ca
      key: k8s_ca.pem
{{- end }}
  rules:
    - host: {{ (index .Values.ingress.hosts 0).name }}
      http:
        paths:
          - path: {{ (index .Values.ingress.hosts 0).path }}
            pathType: {{ (index .Values.ingress.hosts 0).pathType }}
            backend:
              service:
                name: {{ (index .Values.ingress.hosts 0).serviceName | default "sonarqube-sonarqube-dce" }}
                port:
                  number: {{ (index .Values.ingress.hosts 0).servicePort | default 9000 }}
{{- end }}
{{- end }}
