name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Resolve DNS and Set Environment Variable
        run: |
          dns_name="sonarqube.local"
          resolved_ip=$(nslookup $dns_name | awk '/^Address: / { print $2 }')
          echo "SONAR_HOST_URL=$resolved_ip" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
        run: |
          /usr/bin/docker run --name sonarqube-scan \
            -e "SONAR_TOKEN=${SONAR_TOKEN}" \
            -e "SONAR_HOST_URL=${SONAR_HOST_URL}" \
            -v "$(pwd):/github/workspace" \
            sonarsource/sonarqube-scan-action@master
