name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Add the following step to resolve DNS and set the IP as an environment variable
      - name: Resolve DNS to IP
        run: |
          dns_name="sonarqube.local"
          resolved_ip=$(dig +short $dns_name)
          echo "SONAR_HOST_IP=$resolved_ip" >> $GITHUB_ENV

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://sonarqube.local"
