name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create hosts file
        run: echo "35.189.200.234 sonarqube.local" > hosts

      - name: SonarQube Scanner
        run: |
          docker run \
            --rm \
            -e SONAR_HOST_URL="http://sonarqube.local" \
            -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=sonarqube-helm-chart-github" \
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
            -v "$(pwd):/usr/src" \
            -v "$(pwd)/hosts:/etc/hosts" \   # Mount the hosts file into the container
            sonarsource/sonar-scanner-cli
