name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Resolve DNS and Set Environment Variable
        run: |
          set -x  # Enable debug mode
          dns_name="sonarqube.local"
          echo "Resolving DNS for $dns_name"
          resolved_ip=$(nslookup $dns_name | awk '/^Address: / { print $2 }')
          echo "Resolved IP: $resolved_ip"
          echo "SONAR_HOST_URL=$resolved_ip" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Print Environment Variables
        run: |
          echo "SONAR_HOST_URL: $SONAR_HOST_URL"
          echo "SONAR_TOKEN: $SONAR_TOKEN"

      - name: SonarQube Scan
        run: |
          set -x  # Enable debug mode
          echo "SONAR_HOST_URL before scan: $SONAR_HOST_URL"
          docker run --name sonarqube-scan \
            -e "SONAR_TOKEN=$SONAR_TOKEN" \
            -e "SONAR_HOST_URL=$SONAR_HOST_URL" \
            -v "$(pwd):/github/workspace" \
            sonarsource/sonarqube-scan-action@master
