name: Deploy SonarQube

on:
  workflow_run:
    workflows: ["Build SonarQube"]
    types:
      - completed
  push:
    branches:
      - main
    tags:
      - '*' # Push events to matching *, i.e. 1.0, 4.1.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Kubernetes
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config

    - name: Install Helm Chart
      run: |
        helm repo add sonarqube https://ivanov-devops.github.io/sonarqube/
        helm repo update
        #kubectl create namespace sonarqube-dce
        kubectl create namespace sonarqube-dce --dry-run=client -o yaml | kubectl apply -f -
        export JWT_SECRET=${{ secrets.JWT_SECRET }}
        helm upgrade --install -n sonarqube-dce sonarqube sonarqube/sonarqube-dce --set ApplicationNodes.jwtSecret=$JWT_SECRET
