name: Update SonarQube Helm Chart

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Clone original SonarQube Helm chart
      run: |
        git clone https://github.com/SonarSource/helm-chart-sonarqube.git sonarqube
      working-directory: sonarqube

    - name: Copy SonarQube Helm chart files
      run: |
        cp -r helm-chart-sonarqube/* .
        cp -r helm-chart-sonarqube/.github .
      working-directory: sonarqube

    - name: Commit and Push Helm chart update
      run: |
        git config --global user.name "Dimitar Ivanov"
        git config --global user.email "d.ivanov@mmstat.org"
        git add .
        git commit -m "Update SonarQube Helm chart to latest version"
        git push
      working-directory: sonarqube
