name: Update Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*.yaml"
      - "charts/sonarqube-dce/Chart.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Update Chart Version
      run: |
        version=$(git describe --abbrev=0)
        sed -i "s/^version:.*/version: $version/" Chart.yaml
        git config --global user.name "Dimitar Ivanov"
        git config --global user.email "d.ivanov@mmstat.org"
        git add Chart.yaml
        git commit -m "Update chart version to $version"
        git push
